alg:
  save_replay: false
  layer_size: 256
  num_layers: 2
  replay_buffer_size: 1E6
  params:
    start_steps: 200
    eval_freq: 200
    max_steps: 1E6
    num_eval_episodes: 3
    num_eval_timesteps: 200
    batch_size: 512
  trainer:
    initial_temp: .02
    discount: .99
    soft_target_tau: 5E-3
    target_update_period: 2
    actor_lr: 1E-3
    critic_lr: 1E-3
    actor_beta: 0.9
    critic_beta: 0.9
    log_std_min: -10
    log_std_max: 2
    reward_scale: 1
    tau: .005
    use_automatic_entropy_tuning: true